FROM 017894660778.dkr.ecr.eu-central-1.amazonaws.com/sp/dotnet-vanilla:6.0-focal
WORKDIR /app

ENV ASPNETCORE_URLS="http://0.0.0.0:80"

EXPOSE 80

# This is an artifact, generated by bamboo-specs, to be able to override envconsul configuration for secrets
ADD /docker.tar.gz /

ADD /service.tar.gz /app

CMD ["dotnet", "TURI.Contractservice.Api.dll"]